### ISSUE TITLE
[socket2.4]  (三個TableView)  收到新訊息，不會更新

### ISSUE THREAD

**Issue by prototypeSean** [prototypeSean/paeban_ios_beta#20]
沒有從通知（notification）進入ＡＰＰ的話，不會更新badge＆cell

Ａ ＝ 手機
Ｂ ＝ 模擬器

Ａ離開ＡＰＰ
（把螢幕關掉，或者切換到其他ＡＰＰ，或者回到桌面）三種都成立
Ｂ發送訊息給Ａ

Ａ直接打開ＡＰＰ而不是從通知中心進入，則，所有badge以及cell都不會更新，即使切換頁面也不會

**Comment by a110482** [comment]
我只測 my & friend
其他交給你了 啾咪
