### ISSUE TITLE
[socket2.4] [好友清單]刪除功能問題

### ISSUE THREAD

**Issue by prototypeSean** [prototypeSean/paeban_ios_beta#8]
6/26  測試更新

- [x] 1. 從「清單」頁面 FriendTableView 把 cell 刪除 (不是封鎖) 依然收到 Apns 跟 Badge

- [x] 2. 從清單刪除cell要跳出 Alert

- [x] 3. 從「對話」頁面 把對方「封鎖」cell 並沒有被消除，對話依然正常。

- [x] 4. 新訊息進來時badge計算差了1 （還是只有我的是錯的？）

- [x] 5. 刪除 cell 時，沒有即時更新 Badge

**Comment by prototypeSean** [comment]
6/26  測試
2. 從 TableView刪除沒有跳警告視窗
4. 新訊息進來時badge計算差了1 （還是只有我的是錯的？）
5. 刪除 cell 時，沒有即時更新 Badge

**Comment by a110482** [comment]
2  5  fixed 
4 i can't test
